backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "recipes"
    label: "Recipes"
    label_singular: "Recipe"
    folder: "src/pages/recipes"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recipe"}
      - {label: "Name", name: "name" }
      - {label: "Author", name: "author", required: false }
      - {label: "Publish Date", name: "date", widget: "datetime" }
      - {label: "Inspired By", name: "inspiredby", required: false }
      - {label: "Prep Time", name: "preptime", required: false }
      - {label: "Cook Time", name: "cooktime", required: false }
      - {label: "Serving Size", name: "servingsize", required: false }
      - {label: "Image", name: "image", widget: image, required: false }
      - label: Ingredients
        label_singular: Ingredient
        name: ingredients
        widget: list
        allow_add: true
        summary: "{{quantity}} {{measurement}} {{name}}"
        fields:
          - { label: Name, name: name } 
          - { label: Quantity, name: quantity, required: false }
          - label: Measurement
            name: measurement
            widget: select,
            required: false,
            options:
              - { label: "Individual", value: "" }
              - { label: "Dash/Pinch", value: "dash" }
              - { label: "Milligram (mg)", value: "milligram" }
              - { label: "Gram (g)", value: "gram" }
              - { label: "Kilogram (kg)", value: "kilogram" }
              - { label: "Mililiter (mL)", value: "milliliter" }
              - { label: "Liter (L)", value: "liter" }
              - { label: "Teaspoon (tsp)", value: "teaspoon" }
              - { label: "Tablespoon (Tbsp)", value: "tablespoon" }
              - { label: "Cup (c)", value: "cup" }
              - { label: "Pint (pt)", value: "pint" }
              - { label: "Ounce (oz)", value: "ounce" }
              - { label: "Pound (lb)", value: "pound" }
              - { label: "Quart (qt)", value: "quart" }
              - { label: "Gallon (gal)", value: "gallon" }
      - label: Directions
        label_singular: Direction
        name: directions
        widget: list
        allow_add: true
        fields: 
          - { label: Direction, name: direction }